name: Deploy HTML to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2 
     
      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Test SSH Connection
        run: |
         # Create .ssh directory with correct permissions
         mkdir -p ~/.ssh
         chmod 700 ~/.ssh    

      - name: Deploy Files
        run: |
         # Create directory with sudo (if needed)
         ssh -o StrictHostKeyChecking=no \
         -i ~/.ssh/id_rsa \
          ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} \
          "sudo mkdir -p /var/www/html && sudo chown -R $USER:$USER /var/www/html && sudo chmod -R 755 /var/www/html"
    
          # Verify directory exists
          ssh -i ~/.ssh/id_rsa \
          ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} \
          "ls -la /var/www"  # This should show the html directory
    
          # Deploy files
          scp -o StrictHostKeyChecking=no \
          -i ~/.ssh/id_rsa \
          -r ./* \
           ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/var/www/html/
    
           # Verify deployment
           ssh -i ~/.ssh/id_rsa \
           ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} \
           "ls -la /var/www/html"  # Should show your files
      - name: Restart Nginx
        run: |
          ssh -o StrictHostKeyChecking=no \
              -i ~/.ssh/id_rsa \
              ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} \
              "sudo systemctl restart nginx"
